### ISSUE TITLE
Traducciones ??

### ISSUE THREAD

**Issue by margb7** [margb7/Calendario#5]
Puede ser un poquito locura pero con las traducciones se podría usar la lectura de ficheros y no necesariamente tiene que ser dificil.
- Se implemntaría mediante un método que pediría un código asociado a la traducción y que devolvería el texto
- Para cargar las traducciones se usa el scanner
- Para guardar las traducciones en el programa se puede usar una clase nueva, un hashmap o incluso un arraylist
- Para guardar en un fichero se puede poner por cada idioma una línea introductoria con el nombre del idioma y después líneas con un código seguido del texto de la traducción

**Comment by FullOvellas** [comment]
Igual pode ser boa forma de introducir os ficheiros. Igual é algo engorroso de facer pero non parece súper complexo.
Eu imaxino que só se debería soportar a traducción ao iniciar sesión ou crear usuario igual, e logo sería facer como dixeches ti.
O de limitar a funcionalidade así digoo máis que nada por evitar máis bugazos como o que introduciu o que fixen eu co dos bordes das celdas.
Podemos falar con Laura tamén a ver que nos comenta, pero valíalle con ben pouco porque o que comentou foi que os usáramos como log, así que calquera cousa a máis é de ser alumnos modélicos.
